app/Bookstore.Web/Controllers/AddressController.cs
using Bookstore.Domain.Addresses;
using Bookstore.Domain.Customers;
using Bookstore.Web.Helpers;
using Bookstore.Web.ViewModel.Address;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Bookstore.Web.Controllers
{
    public class AddressController : Controller
    {
        private readonly IAddressService addressService;

        public AddressController(IAddressService addressService)
        {
            this.addressService = addressService;
        }

        public async Task<IActionResult> Index()
        {
            var addresses = await addressService.GetAddressesAsync(User.GetSub());

            return View(new AddressIndexViewModel(addresses));
        }

        public IActionResult Create(string returnUrl)
        {
            var model = new AddressCreateUpdateViewModel(returnUrl);

            return View("CreateUpdate", model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddressCreateUpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var dto = new CreateAddressDto(model.AddressLine1, model.AddressLine2, model.City, model.State, model.Country, model.ZipCode, User.GetSub());

            await addressService.CreateAddressAsync(dto);

            return Redirect(model.ReturnUrl);
        }

        public async Task<IActionResult> Update(int id, string returnUrl)
        {
            var address = await addressService.GetAddressAsync(User.GetSub(), id);

            return View("CreateUpdate", new AddressCreateUpdateViewModel(address, returnUrl));
        }

        [HttpPost]
        public async Task<IActionResult> Update(AddressCreateUpdateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var dto = new UpdateAddressDto(model.Id, model.AddressLine1, model.AddressLine2, model.City, model.State, model.Country, model.ZipCode, User.GetSub());

            await addressService.UpdateAddressAsync(dto);

            return Redirect(model.ReturnUrl);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var dto = new DeleteAddressDto(id, User.GetSub());

            await addressService.DeleteAddressAsync(dto);

            this.SetNotification("Address deleted");

            return RedirectToAction(nameof(Index));
        }
    }
}

app/Bookstore.Web/Controllers/CheckoutController.cs
using Bookstore.Domain.Addresses;
using Bookstore.Domain.Carts;
using Bookstore.Domain.Orders;
using Bookstore.Web.Helpers;
using Bookstore.Web.ViewModel.Checkout;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Bookstore.Web.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IAddressService addressService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IOrderService orderService;

        public CheckoutController(IShoppingCartService shoppingCartService,
                                  IOrderService orderService,
                                  IAddressService addressService)
        {
            this.shoppingCartService = shoppingCartService;
            this.orderService = orderService;
            this.addressService = addressService;
        }

        public async Task<IActionResult> Index()
        {
            var shoppingCart = await shoppingCartService.GetShoppingCartAsync(HttpContext.GetShoppingCartCorrelationId());
            var addresses = await addressService.GetAddressesAsync(User.GetSub());

            return View(new CheckoutIndexViewModel(shoppingCart, addresses));
        }

        [HttpPost]
        public async Task<IActionResult> Index(CheckoutIndexViewModel model)
        {
            var dto = new CreateOrderDto(User.GetSub(), HttpContext.GetShoppingCartCorrelationId(), model.SelectedAddressId);

            var orderId = await orderService.CreateOrderAsync(dto);

            return RedirectToAction("Finished", new { orderId });
        }

        public async Task<IActionResult> Finished(int orderId)
        {
            var order = await orderService.GetOrderAsync(orderId);

            return View(new CheckoutFinishedViewModel(order));
        }
    }
}

app/Bookstore.Web/Views/Checkout/Finished.cshtml
@model Bookstore.Web.ViewModel.Checkout.CheckoutFinishedViewModel

<div class="panel-body">
    <table width="100%" height="100%" cellpadding="0" cellspacing="0">
        <tr>
            <td valign="middle" align="center">
                <h2>Order Placed Successfully!</h2>

            </td>

        </tr>
    </table>

    <br />
    <br />
    <div class="container" style="text-align: center">
        <ul class="time-horizontal">
            <li style="color:red"><b></b>Cart</li>
            <li style="color:red"><b></b>Choose Address</li>
            <li style="color:red"><b></b>Finish</li>
        </ul>
    </div>
    <br />
    <br />

    <table class="table" width="700">
        <thead>
        <tr>
            <th>
                Cover
            </th>
            <th>
                name
            </th>
            <th>
                price
            </th>
            <th>quantity</th>
            <th>total</th>
        </tr>
        </thead>

        <tbody>
        @foreach (var item in Model.Items)
        {
            var total = item.Price * item.Quantity;
            <tr>
                <td>
                    <img src="@item.Url" height="80" width="50" onerror="this.onerror=null;this.src='/images/default_c.jpg';" />
                </td>
                <td>
                    @item.Bookname
                </td>

                <td>
                    $@item.Price
                </td>

                <td>
                    @item.Quantity
                </td>

                <td>
                    $@total
                </td>
            </tr>
        }
        </tbody>
    </table>

    <a asp-controller="Home" asp-action="Index">Back to home</a>
</div>

app/Bookstore.Web/Views/Checkout/Index.cshtml
@model Bookstore.Web.ViewModel.Checkout.CheckoutIndexViewModel

<div class="panel-body">

    <h1>Finish your order</h1>
    <br />
    <br />
    <div class="container" style="text-align: center">

        <ul class="time-horizontal">
            <li style="color:red"><b></b>Cart</li>
            <li style="color:red"><b></b>Choose Address</li>
            <li>
                <p></p>Finish
            </li>

        </ul>
    </div>
    <br />
    <br />
    <br />

    <div>
        <h2>Total price :$@Model.Total</h2>
    </div>

    <form method="post">
        <table class="table">
            <thead>
            <tr>
                <th></th>
                <th>Address Line 1</th>
                <th>Address Line 2</th>
                <th>City</th>
                <th>State</th>
                <th>Country</th>
                <th>ZipCode</th>
                <th></th>
            </tr>
            </thead>
            <tbody>

            @foreach (var address in Model.Addresses)
            {
                <tr>
                    <td>
                        <input type="radio" asp-for="@Model.SelectedAddressId" value="@address.Id" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.AddressLine1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.AddressLine2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.Country)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => address.ZipCode)
                    </td>
                    <td>
                        <a asp-action="Update" asp-controller="Address" asp-route-id="@address.Id" asp-route-returnUrl="@Url.Action()">Edit</a>
                    </td>
                </tr>
            }

            @if (Model.Addresses.Count() == 0)
            {
                <input type="submit" value="Finish your order" class="btn" disabled />
                <p style="color:red"> Add an Address to proceed to checkout </p>
            }
            else
            {
                <input type="submit" value="Finish your order" class="btn" />
            }
            </tbody>
        </table>
    </form>

    <div>
        <p style="text-align: center">
            <a asp-action="Create" asp-controller="Address" asp-route-returnUrl="@Url.Action()">Add address</a>
        </p>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>Cover</th>
            <th>name</th>
            <th>price</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.ShoppingCartItems)
        {
            <tr>
                <td>
                    <img src="@item.ImageUrl" height="80" width="50" onerror="this.onerror=null;this.src='/images/default_c.jpg';" />
                </td>
                <td>
                    <span class="@(item.OutOfStock ? "text-danger" : "")">@item.BookName</span>

                    @if (item.OutOfStock)
                    {
                        <p class="text-danger"><small>Out of stock</small></p>
                    }
                </td>

                <td>
                    <span style="@(item.OutOfStock ? "text-decoration: line-through;":"")">$@item.Price</span>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>